version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.service
    image: "bert-service:${TAG}"
    ports:
      - "5000:5000"
    command:
      ["gunicorn", "server:app", "-b", "0.0.0.0:5000", "--timeout", "120"]
